### ISSUE TITLE
Unable to ingest metrics from prometheus

### ISSUE THREAD

**Issue by vSivarajah93** [waliaabhishek/chitragupta#7]
Hello!

I am trying to follow the README. I have created a service account with organizationadmin and metricsViewer and populated the `.my_env` with the api keys and secret.

By looking into the logs of the prometheus feeder i can see that its failing the readiness check:
This is parts of the `.my_env` i think will be relevant.
```
 METRICS_API_SERVER_URL=api.telemetry.confluent.cloud/v2/metrics/cloud/export
#  METRICS_API_SERVER_URL=http://localhost:9091

METRICS_API_SERVER_ENABLE_AUTH=True
# METRICS_API_SERVER_ENABLE_AUTH=True

#HTTPBasic is the only supported auth type as of now. Do NOT change this
METRICS_API_SERVER_AUTH_TYPE=HTTPBasicAuth                              

METRICS_API_SERVER_AUTH_USERNAME=xxxxx
# METRICS_API_SERVER_AUTH_USERNAME=admin

METRICS_API_SERVER_AUTH_PASSWORD=xxxx
# METRICS_API_SERVER_AUTH_PASSWORD=password

#Do NOT change this if you will be using the provided docker-compose file
CHARGEBACK_SERVER_URL=http://prometheus_for_chargeback:9090             

```

I also looked into the logs of the chargeback-handler application:

```
Traceback (most recent call last):
  File "/app/main.py", line 23, in <module>
    execute_workflow(arg_flags)
  File "/app/helpers.py", line 35, in add_entry_exit_logs
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/app/workflow_runner.py", line 134, in execute_workflow
    ccloud_orgs = CCloudOrgList(
                  ^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/app/ccloud/org.py", line 225, in __post_init__
    temp = CCloudOrg(
           ^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/app/ccloud/org.py", line 100, in __post_init__
    self.billing_handler = CCloudBillingHandler(
                           ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __init__
  File "/app/data_processing/data_handlers/billing_api_handler.py", line 73, in __post_init__
    self.read_all(start_date=self.start_date, end_date=end_date)
  File "/app/helpers.py", line 35, in add_entry_exit_logs
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/app/data_processing/data_handlers/billing_api_handler.py", line 158, in read_all
    temp_data = [
                ^
  File "/app/data_processing/data_handlers/billing_api_handler.py", line 161, in <listcomp>
    BILLING_API_COLUMNS.env_id: item["resource"]["environment"]["id"],
                                ~~~~^^^^^^^^^^^^
KeyError: 'resource'

```

Have i misconfigured something?

**Comment by waliaabhishek** [comment]
## Issue 1

Looks like there was some newer billing RESOURCE TYPE added to the Billing API response. I can definitely take a look at it. Will it be possible for you to enable DEBUG log and post the log file somewhere? Make sure you redact your keys and secrets from the log file before you post it. 

If you are running it via docker compose, you can update the LOG value to DEBUG [here](https://github.com/waliaabhishek/ccloud-chargeback-helper/blob/764c0bd161845745761777c17824f65564d092fb/deployables/assets/chargeback_handler/config/config_internal.yaml#L5) and the next line to `True` and restart the docker compose.

P.S: I am working on making the Log value configurable via the env file as well, so that its value can be changed as needed.

--- 
## Issue 2

> METRICS_API_SERVER_URL=api.telemetry.confluent.cloud/v2/metrics/cloud/export 

Also, its mentioned in the docs that the code does not connect Metrics API directly. You will need to provide it with URL of the Metrics API Prom server or use the chargeback prom server url if you dont have scraping for Metrics API setup.

**Comment by waliaabhishek** [comment]
@vSivarajah93 : I have fixed an edge case for Billing API fetch use case where some of the required parameters were missing. Please try out v1.0.4 and let me know if you still see the error.
